name: 'Testing OpenID'

on:
  workflow_dispatch:
    branches: [ "qa" ]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  awslogincheck:
    name: 'aws login'
    runs-on: ubuntu-latest
    environment: qa
      
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # AWS login sections
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with: 
        role-to-assume: ${{ secrets.role_to_assume_openid }}
        audience: sts.amazonaws.com
        role-session-name: sessionfeenixdv
        aws-region: ${{ vars.REGION }}

    - name: Print assume role name
      run: aws sts get-caller-identity
    
    - name: List s3 buckets
      run: aws s3 ls
    
