name: "TFSEC"

on:
  workflow_dispatch:
    branches: [ "qa" ]
  pull_request:
  
permissions: 
  contents: read
  id-token: write

jobs:
  tfsec:
    name: tfsec security scan
    runs-on: ubuntu-latest
    environment: qa
    defaults:
      run:
        working-directory: ./staging
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: tfsec
      uses: tfsec/tfsec-sarif-action@master
      continue-on-error: true
      with:
        sarif_file: tfsec.sarif                

    # - name: Upload SARIF file
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     # Path to SARIF file relative to the root of the repository
    #     sarif_file: tfsec.sarif
